version: '3.8'
services:
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: laravelteste
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "9906:3306"
        volumes:
            - ./dbdata:/var/lib/mysql
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
          - '8001:80'
      restart: always
      environment:
          PMA_HOST: db
      depends_on:
          - db
